spring:
  graphql:
    schema:
      printer:
        enabled: true
  r2dbc:
    url: r2dbcs:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: jcohy1203


